#!/usr/local/bin/bash

# Prepend timestamp to `history`
HISTTIMEFORMAT="%d/%m/%y %T "

# sources
for FILE in ~/.dotfiles/bin/bash-*; do
  if [[ -r $FILE && -f $FILE ]]; then
    . $FILE
  fi
done
unset FILE

eval "$(rbenv init -)"
eval "$(thefuck --alias)"
