#!/usr/bin/env bash

# nice opts
for OPTION in nocaseglob globstar histappend cmdhist cdspell dirspell autocd cdable_vars; do
  shopt -s "$OPTION" 2> /dev/null
done
unset OPTION


# navigation
CDPATH=".:~/Code"


# History formatting
HISTTIMEFORMAT="%d/%m/%y %T "      # timestamp
HISTSIZE=500000                    # num lines
HISTFILESIZE=100000                # num bytes
HISTCONTROL="erasedups:ignoreboth" # prevent dupes
HISTIGNORE="&:[ ]*:cd:ls:history:ga:gdn:gup:gs:clear:screen:" # ignore boring cmds
bind Space:magic-space # expand inline


# autocompletion
bind "set completion-ignore-case on"
bind "set completion-map-case on"
bind "set show-all-if-ambiguous on"


# binary paths
export RBENV_ROOT=/usr/local/var/rbenv
export PYTHONPATH=/usr/local/bin/python
export NODE_PATH=/usr/local/lib/node_modules:$NODE_PATH
export NVM_DIR="$HOME/.nvm"


# sources @todo: fix dirname
for FILE in ~/.dotfiles/{bin/*,bin}/bash-*; do
  test -f $FILE && . $FILE
done


# remove path dupes
type _tidyUpPath &> /dev/null && _tidyUpPath


# here be dragons
type rbenv   &> /dev/null && eval "$(rbenv init -)"
type thefuck &> /dev/null && eval "$(thefuck --alias)"
