#!/usr/bin/env bash

# nice opts
for OPTION in nocaseglob globstar histappend cmdhist cdspell dirspell autocd cdable_vars; do
  shopt -s "$OPTION" 2> /dev/null
done
unset OPTION


# navigation
CDPATH=".:~/Code"


# History formatting
HISTTIMEFORMAT="%d/%m/%y %T "      # timestamp
HISTSIZE=500000                    # num lines
HISTFILESIZE=100000                # num bytes
HISTCONTROL="erasedups:ignoreboth" # prevent dupes
HISTIGNORE="&:[ ]*:cd:ls:history:ga:gdn:gup:gs:clear:screen:" # ignore boring cmds


# autocompletion
bind Space:magic-space # expand inline
bind "set completion-ignore-case on"
bind "set completion-map-case on"
bind "set show-all-if-ambiguous on"


# paths
export PHPENV_ROOT="$HOME/.phpenv"
export RBENV_ROOT=/usr/local/var/rbenv
export PYTHONPATH=/usr/local/bin/python
export NODE_PATH="/usr/local/lib/node_modules:$NODE_PATH"
export GIT_TEMPLATE_DIR=/Users/Jon/Code/Tools/hooks
export NVM_DIR="$HOME/.nvm"
export HOMEBREW_EDITOR="code"
export ANDROID_HOME="$HOME/Library/Android/sdk"
export WP_TESTS_DIR="$HOME/Code/wptest/wordpress-tests-lib"
export WP_CORE_DIR="$HOME/Code/wptest/wordpress"

# compiler flags
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
#pkg-config flags
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

# sources @todo: fix dirname
for FILE in ~/.dotfiles/{bin/*,bin}/bash-*; do
  # shellcheck source=/dev/null
  test -f "$FILE" && . "$FILE"
done


# remove path dupes
type _tidyUpPath &> /dev/null && _tidyUpPath


# here be dragons
type rbenv &> /dev/null && eval "$(rbenv init -)"
